apiVersion: v1
kind: Service
metadata:
  name: accountservice
  labels:
    app: accountservice # create a label for the service
spec:
  ports:
    - port: 6767
      protocol: TCP
  selector:
    app: accountservice # add any pod with `app=accountservice` to this service
