apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  labels:
    app: quotes # create a label for the service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: quotes # add any pod with `app=accountservice` to this service
